# Generated by Django 4.2.19 on 2025-02-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackupAnalysisTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary_key", models.IntegerField(unique=True)),
                ("property_primary_key", models.IntegerField()),
                ("phone_number", models.CharField(max_length=20)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("progress", models.FloatField(default=0.0)),
                ("stage", models.CharField(blank=True, max_length=50)),
                ("stage_progress", models.JSONField(default=dict)),
                ("trigger_analysis", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BackupProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary_key", models.IntegerField(unique=True)),
                ("url", models.URLField()),
                (
                    "share_token",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("bedrooms", models.IntegerField(blank=True, null=True)),
                ("bathrooms", models.IntegerField(blank=True, null=True)),
                ("size", models.CharField(blank=True, max_length=100, null=True)),
                ("house_type", models.CharField(blank=True, max_length=100, null=True)),
                ("agent", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("reviewed_description", models.TextField(blank=True, null=True)),
                ("description_analysis", models.JSONField(blank=True, null=True)),
                ("sentiment_analysis", models.JSONField(blank=True, null=True)),
                (
                    "listing_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "time_on_market",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("features", models.TextField(blank=True, null=True)),
                ("floorplan_urls", models.JSONField(blank=True, default=list)),
                ("overall_condition", models.JSONField(blank=True, null=True)),
                ("detailed_analysis", models.JSONField(blank=True, null=True)),
                ("failed_downloads", models.JSONField(default=list)),
                ("image_urls", models.JSONField(default=list)),
                ("overall_analysis", models.JSONField(blank=True, null=True)),
                (
                    "analysis_source",
                    models.CharField(
                        choices=[("email", "Email"), ("original", "Original")],
                        default="original",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BackupScrapingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary_key", models.IntegerField(unique=True)),
                ("url", models.URLField()),
                ("source", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=20)),
                ("callback_url", models.URLField(blank=True, null=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("property_id", models.IntegerField(blank=True, null=True)),
                ("scraped_property_id", models.IntegerField(blank=True, null=True)),
                ("task_id", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
