# Generated by Django 4.2.8 on 2025-04-04 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backup", "0004_analysistask_csvroomdimensions_csvroompixeldata_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalTotalAreaData",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("area_name", models.CharField(blank=True, max_length=500, null=True)),
                ("square_meters", models.FloatField(blank=True, null=True)),
                ("square_feet", models.FloatField(blank=True, null=True)),
                ("total_floors", models.IntegerField(blank=True, null=True)),
                ("total_named_rooms", models.IntegerField(blank=True, null=True)),
                ("total_segments", models.IntegerField(blank=True, null=True)),
                ("total_points", models.IntegerField(blank=True, null=True)),
                ("total_objects", models.IntegerField(blank=True, null=True)),
                ("total_door_objects", models.IntegerField(blank=True, null=True)),
                ("total_window_objects", models.IntegerField(blank=True, null=True)),
                ("total_stair_objects", models.IntegerField(blank=True, null=True)),
                ("list_of_objects", models.TextField(blank=True, null=True)),
                ("total_actual_pixels", models.FloatField(blank=True, null=True)),
                ("metric_scale", models.FloatField(blank=True, null=True)),
                ("imperial_scale", models.FloatField(blank=True, null=True)),
                ("input_image_tokens", models.IntegerField(blank=True, null=True)),
                ("input_text_tokens", models.IntegerField(blank=True, null=True)),
                ("output_text_tokens", models.IntegerField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "all_floors_data",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="backup.allfloorsdata",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Backup Total Area Data",
                "verbose_name_plural": "historical Backup Total Area Data",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProperty",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("primary_key", models.IntegerField(db_index=True)),
                ("url", models.URLField()),
                (
                    "share_token",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("bedrooms", models.IntegerField(blank=True, null=True)),
                ("bathrooms", models.IntegerField(blank=True, null=True)),
                ("size", models.CharField(blank=True, max_length=100, null=True)),
                ("house_type", models.CharField(blank=True, max_length=100, null=True)),
                ("agent", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("reviewed_description", models.TextField(blank=True, null=True)),
                ("description_analysis", models.JSONField(blank=True, null=True)),
                ("sentiment_analysis", models.JSONField(blank=True, null=True)),
                (
                    "listing_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "time_on_market",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("features", models.TextField(blank=True, null=True)),
                ("floorplan_urls", models.JSONField(blank=True, default=list)),
                ("overall_condition", models.JSONField(blank=True, null=True)),
                ("detailed_analysis", models.JSONField(blank=True, null=True)),
                ("failed_downloads", models.JSONField(default=list)),
                ("image_urls", models.JSONField(default=list)),
                ("overall_analysis", models.JSONField(blank=True, null=True)),
                (
                    "analysis_source",
                    models.CharField(
                        choices=[("email", "Email"), ("original", "Original")],
                        default="original",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical property",
                "verbose_name_plural": "historical propertys",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPlanFloor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("floor", models.CharField(max_length=255)),
                ("label_me_url", models.URLField()),
                ("json_file_url", models.URLField()),
                ("image_url", models.URLField()),
                ("labelme_image_url", models.URLField()),
                ("csv_url", models.URLField()),
                ("image_side_by_side_url", models.URLField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "floor_plan",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="backup.floorplan",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical plan floor",
                "verbose_name_plural": "historical plan floors",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFloorPlanAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("message", models.CharField(max_length=255)),
                ("user_id", models.CharField(max_length=255)),
                ("property_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical floor plan analysis result",
                "verbose_name_plural": "historical floor plan analysis results",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFloorPlan",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("floorplan_id", models.CharField(max_length=255)),
                ("original_url", models.URLField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "analysis_result",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="backup.floorplananalysisresult",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical floor plan",
                "verbose_name_plural": "historical floor plans",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCsvRoomScalingFactors",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("scale_metric", models.FloatField(blank=True, null=True)),
                ("scale_imperial", models.FloatField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "csv_room",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="backup.csvroom",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical csv room scaling factors",
                "verbose_name_plural": "historical csv room scaling factorss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCsvRoomPixelData",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("min_x_pixels", models.FloatField(blank=True, null=True)),
                ("min_y_pixels", models.FloatField(blank=True, null=True)),
                ("max_x_pixels", models.FloatField(blank=True, null=True)),
                ("max_y_pixels", models.FloatField(blank=True, null=True)),
                ("max_area_pixels", models.FloatField(blank=True, null=True)),
                ("actual_area_pixels", models.FloatField(blank=True, null=True)),
                ("pixel_ratio", models.FloatField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "csv_room",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="backup.csvroom",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical csv room pixel data",
                "verbose_name_plural": "historical csv room pixel datas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCsvRoomDimensions",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "dimensions_imperial",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dimensions_metric",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("max_area_metric", models.FloatField(blank=True, null=True)),
                ("max_area_imperial", models.FloatField(blank=True, null=True)),
                ("calculated_sq_area_metric", models.FloatField(blank=True, null=True)),
                (
                    "calculated_floor_total_sq_area_metric",
                    models.FloatField(blank=True, null=True),
                ),
                ("calculated_area_imperial", models.FloatField(blank=True, null=True)),
                (
                    "calculated_floor_total_sq_area_imperial",
                    models.FloatField(blank=True, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "csv_room",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="backup.csvroom",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical csv room dimensions",
                "verbose_name_plural": "historical csv room dimensionss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCsvRoom",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("room_name", models.CharField(blank=True, max_length=100, null=True)),
                ("is_segment", models.CharField(blank=True, max_length=50, null=True)),
                ("room_id", models.FloatField(blank=True, null=True)),
                ("no_of_doors", models.FloatField(blank=True, null=True)),
                ("no_of_windows", models.FloatField(blank=True, null=True)),
                ("no_of_room_points", models.FloatField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "csv_floor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="backup.csvfloor",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical csv room",
                "verbose_name_plural": "historical csv rooms",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCsvFloor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("floor_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "calculated_total_area_metric",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "calculated_total_area_imperial",
                    models.FloatField(blank=True, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "all_floors_data",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="backup.allfloorsdata",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical csv floor",
                "verbose_name_plural": "historical csv floors",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAnalysisTask",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("primary_key", models.IntegerField(db_index=True)),
                ("property_primary_key", models.IntegerField()),
                ("phone_number", models.CharField(max_length=20)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("progress", models.FloatField(default=0.0)),
                ("stage", models.CharField(blank=True, max_length=50)),
                ("stage_progress", models.JSONField(default=dict)),
                ("trigger_analysis", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical analysis task",
                "verbose_name_plural": "historical analysis tasks",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAllFloorsData",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("json_file_url", models.URLField()),
                ("csv_url", models.URLField()),
                ("total_area_csv_url", models.URLField()),
                ("image_labelme_side_by_side_url", models.URLField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "floor_plan",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="backup.floorplan",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical all floors data",
                "verbose_name_plural": "historical all floors datas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAllFloorsCsvRawRow",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "floor_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("room_name", models.CharField(blank=True, max_length=100, null=True)),
                ("is_segment", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "dimensions_imperial",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dimensions_metric",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("room_id", models.FloatField(blank=True, db_index=True, null=True)),
                ("no_of_door", models.FloatField(blank=True, null=True)),
                ("no_of_window", models.FloatField(blank=True, null=True)),
                ("no_of_room_points", models.FloatField(blank=True, null=True)),
                ("min_x_pixels", models.FloatField(blank=True, null=True)),
                ("min_y_pixels", models.FloatField(blank=True, null=True)),
                ("max_x_pixels", models.FloatField(blank=True, null=True)),
                ("max_y_pixels", models.FloatField(blank=True, null=True)),
                ("max_area_metric", models.FloatField(blank=True, null=True)),
                ("max_area_imperial", models.FloatField(blank=True, null=True)),
                ("max_area_pixels", models.FloatField(blank=True, null=True)),
                ("actual_area_pixels", models.FloatField(blank=True, null=True)),
                ("pixel_ratio", models.FloatField(blank=True, null=True)),
                ("scale_metric", models.FloatField(blank=True, null=True)),
                ("scale_imperial", models.FloatField(blank=True, null=True)),
                ("calculated_sq_area_metric", models.FloatField(blank=True, null=True)),
                (
                    "calculated_floor_total_sq_area_metric",
                    models.FloatField(blank=True, null=True),
                ),
                ("calculated_area_imperial", models.FloatField(blank=True, null=True)),
                (
                    "calculated_floor_total_sq_area_imperial",
                    models.FloatField(blank=True, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "all_floors_data",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="backup.allfloorsdata",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Backup All Floors CSV Raw Row",
                "verbose_name_plural": "historical Backup All Floors CSV Raw Rows",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TotalAreaData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("area_name", models.CharField(blank=True, max_length=500, null=True)),
                ("square_meters", models.FloatField(blank=True, null=True)),
                ("square_feet", models.FloatField(blank=True, null=True)),
                ("total_floors", models.IntegerField(blank=True, null=True)),
                ("total_named_rooms", models.IntegerField(blank=True, null=True)),
                ("total_segments", models.IntegerField(blank=True, null=True)),
                ("total_points", models.IntegerField(blank=True, null=True)),
                ("total_objects", models.IntegerField(blank=True, null=True)),
                ("total_door_objects", models.IntegerField(blank=True, null=True)),
                ("total_window_objects", models.IntegerField(blank=True, null=True)),
                ("total_stair_objects", models.IntegerField(blank=True, null=True)),
                ("list_of_objects", models.TextField(blank=True, null=True)),
                ("total_actual_pixels", models.FloatField(blank=True, null=True)),
                ("metric_scale", models.FloatField(blank=True, null=True)),
                ("imperial_scale", models.FloatField(blank=True, null=True)),
                ("input_image_tokens", models.IntegerField(blank=True, null=True)),
                ("input_text_tokens", models.IntegerField(blank=True, null=True)),
                ("output_text_tokens", models.IntegerField(blank=True, null=True)),
                (
                    "all_floors_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_total_area_data",
                        to="backup.allfloorsdata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backup Total Area Data",
                "verbose_name_plural": "Backup Total Area Data",
                "unique_together": {("all_floors_data", "area_name")},
            },
        ),
        migrations.CreateModel(
            name="AllFloorsCsvRawRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "floor_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("room_name", models.CharField(blank=True, max_length=100, null=True)),
                ("is_segment", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "dimensions_imperial",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dimensions_metric",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("room_id", models.FloatField(blank=True, db_index=True, null=True)),
                ("no_of_door", models.FloatField(blank=True, null=True)),
                ("no_of_window", models.FloatField(blank=True, null=True)),
                ("no_of_room_points", models.FloatField(blank=True, null=True)),
                ("min_x_pixels", models.FloatField(blank=True, null=True)),
                ("min_y_pixels", models.FloatField(blank=True, null=True)),
                ("max_x_pixels", models.FloatField(blank=True, null=True)),
                ("max_y_pixels", models.FloatField(blank=True, null=True)),
                ("max_area_metric", models.FloatField(blank=True, null=True)),
                ("max_area_imperial", models.FloatField(blank=True, null=True)),
                ("max_area_pixels", models.FloatField(blank=True, null=True)),
                ("actual_area_pixels", models.FloatField(blank=True, null=True)),
                ("pixel_ratio", models.FloatField(blank=True, null=True)),
                ("scale_metric", models.FloatField(blank=True, null=True)),
                ("scale_imperial", models.FloatField(blank=True, null=True)),
                ("calculated_sq_area_metric", models.FloatField(blank=True, null=True)),
                (
                    "calculated_floor_total_sq_area_metric",
                    models.FloatField(blank=True, null=True),
                ),
                ("calculated_area_imperial", models.FloatField(blank=True, null=True)),
                (
                    "calculated_floor_total_sq_area_imperial",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "all_floors_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_all_floors_raw_rows",
                        to="backup.allfloorsdata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backup All Floors CSV Raw Row",
                "verbose_name_plural": "Backup All Floors CSV Raw Rows",
                "indexes": [
                    models.Index(
                        fields=["all_floors_data", "floor_name"],
                        name="backup_allf_all_flo_67fd4d_idx",
                    ),
                    models.Index(
                        fields=["all_floors_data", "room_id"],
                        name="backup_allf_all_flo_220fd6_idx",
                    ),
                ],
            },
        ),
    ]
