# Generated by Django 4.2.8 on 2025-04-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backup", "0005_historicaltotalareadata_historicalproperty_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="floorplan",
            options={"verbose_name_plural": "Floor Plans"},
        ),
        migrations.AlterModelOptions(
            name="floorplananalysisresult",
            options={"verbose_name_plural": "Floor Plan Analysis Results"},
        ),
        migrations.AlterModelOptions(
            name="historicalfloorplan",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical floor plan",
                "verbose_name_plural": "historical Floor Plans",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalfloorplananalysisresult",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical floor plan analysis result",
                "verbose_name_plural": "historical Floor Plan Analysis Results",
            },
        ),
        migrations.AlterUniqueTogether(
            name="floorplan",
            unique_together={("analysis_result", "floorplan_id")},
        ),
        migrations.AlterUniqueTogether(
            name="floorplananalysisresult",
            unique_together={("user_id", "property_id")},
        ),
        migrations.AddIndex(
            model_name="floorplan",
            index=models.Index(
                fields=["floorplan_id"], name="backup_floo_floorpl_da43f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="floorplananalysisresult",
            index=models.Index(
                fields=["user_id", "property_id"], name="backup_floo_user_id_07f41b_idx"
            ),
        ),
    ]
