# Generated by Django 4.2.8 on 2025-04-15 14:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backup", "0006_alter_floorplan_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AllFloorsCsvRawRow",
            new_name="AllFloorsCsvData",
        ),
        migrations.RenameModel(
            old_name="HistoricalAllFloorsCsvRawRow",
            new_name="HistoricalAllFloorsCsvData",
        ),
        migrations.RenameModel(
            old_name="HistoricalTotalAreaData",
            new_name="HistoricalTotalAreasCsvData",
        ),
        migrations.RenameModel(
            old_name="TotalAreaData",
            new_name="TotalAreasCsvData",
        ),
        migrations.RenameIndex(
            model_name="allfloorscsvdata",
            new_name="backup_allf_all_flo_c57ce0_idx",
            old_name="backup_allf_all_flo_67fd4d_idx",
        ),
        migrations.RenameIndex(
            model_name="allfloorscsvdata",
            new_name="backup_allf_all_flo_37df0d_idx",
            old_name="backup_allf_all_flo_220fd6_idx",
        ),
    ]
