# Generated by Django 4.2.8 on 2025-04-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backup", "0008_rename_csv_data_tables"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allfloorsdata",
            options={},
        ),
        migrations.AlterModelOptions(
            name="analysistask",
            options={
                "verbose_name": "Analysis Task",
                "verbose_name_plural": "Analysis Tasks",
            },
        ),
        migrations.AlterModelOptions(
            name="csvfloor",
            options={},
        ),
        migrations.AlterModelOptions(
            name="csvroom",
            options={},
        ),
        migrations.AlterModelOptions(
            name="csvroomdimensions",
            options={},
        ),
        migrations.AlterModelOptions(
            name="csvroompixeldata",
            options={},
        ),
        migrations.AlterModelOptions(
            name="csvroomscalingfactors",
            options={},
        ),
        migrations.AlterModelOptions(
            name="floorplan",
            options={
                "verbose_name": "Floor Plan",
                "verbose_name_plural": "Floor Plans",
            },
        ),
        migrations.AlterModelOptions(
            name="floorplananalysisresult",
            options={
                "verbose_name": "Floor Plan Analysis Result",
                "verbose_name_plural": "Floor Plan Analysis Results",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalanalysistask",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Analysis Task",
                "verbose_name_plural": "historical Analysis Tasks",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalfloorplan",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Floor Plan",
                "verbose_name_plural": "historical Floor Plans",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalfloorplananalysisresult",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Floor Plan Analysis Result",
                "verbose_name_plural": "historical Floor Plan Analysis Results",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalproperty",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Property Data",
                "verbose_name_plural": "historical Property Data Records",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaltotalareascsvdata",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Total Area CSV Data",
                "verbose_name_plural": "historical Total Area CSV Data",
            },
        ),
        migrations.AlterModelOptions(
            name="planfloor",
            options={},
        ),
        migrations.AlterModelOptions(
            name="property",
            options={
                "verbose_name": "Property Data",
                "verbose_name_plural": "Property Data Records",
            },
        ),
        migrations.AlterModelOptions(
            name="scrapingjob",
            options={
                "verbose_name": "Scraping Job",
                "verbose_name_plural": "Scraping Jobs",
            },
        ),
        migrations.AlterModelOptions(
            name="totalareascsvdata",
            options={
                "verbose_name": "Total Area CSV Data",
                "verbose_name_plural": "Total Area CSV Data",
            },
        ),
        migrations.RenameIndex(
            model_name="floorplan",
            new_name="sdb_floorpl_floorpl_43eb96_idx",
            old_name="backup_floo_floorpl_da43f3_idx",
        ),
        migrations.RenameIndex(
            model_name="floorplananalysisresult",
            new_name="sdb_fp_anal_user_id_7357dd_idx",
            old_name="backup_floo_user_id_07f41b_idx",
        ),
        migrations.AlterModelTable(
            name="allfloorsdata",
            table="sdb_fp_all_floors_data",
        ),
        migrations.AlterModelTable(
            name="analysistask",
            table="sdb_analysis_tasks",
        ),
        migrations.AlterModelTable(
            name="csvfloor",
            table="sdb_fp_csv_floors",
        ),
        migrations.AlterModelTable(
            name="csvroom",
            table="sdb_fp_csv_rooms",
        ),
        migrations.AlterModelTable(
            name="csvroomdimensions",
            table="sdb_fp_csv_room_dimensions",
        ),
        migrations.AlterModelTable(
            name="csvroompixeldata",
            table="sdb_fp_csv_room_pixel_data",
        ),
        migrations.AlterModelTable(
            name="csvroomscalingfactors",
            table="sdb_fp_csv_room_scaling_factors",
        ),
        migrations.AlterModelTable(
            name="floorplan",
            table="sdb_floorplans",
        ),
        migrations.AlterModelTable(
            name="floorplananalysisresult",
            table="sdb_fp_analysis_results",
        ),
        migrations.AlterModelTable(
            name="historicalallfloorsdata",
            table="history_sdb_fp_all_floors_data",
        ),
        migrations.AlterModelTable(
            name="historicalanalysistask",
            table="history_sdb_analysis_tasks",
        ),
        migrations.AlterModelTable(
            name="historicalcsvfloor",
            table="history_sdb_fp_csv_floors",
        ),
        migrations.AlterModelTable(
            name="historicalcsvroom",
            table="history_sdb_fp_csv_rooms",
        ),
        migrations.AlterModelTable(
            name="historicalcsvroomdimensions",
            table="history_sdb_fp_csv_room_dimensions",
        ),
        migrations.AlterModelTable(
            name="historicalcsvroompixeldata",
            table="history_sdb_fp_csv_room_pixel_data",
        ),
        migrations.AlterModelTable(
            name="historicalcsvroomscalingfactors",
            table="history_sdb_fp_csv_room_scaling_factors",
        ),
        migrations.AlterModelTable(
            name="historicalfloorplan",
            table="history_sdb_floorplans",
        ),
        migrations.AlterModelTable(
            name="historicalfloorplananalysisresult",
            table="history_sdb_fp_analysis_results",
        ),
        migrations.AlterModelTable(
            name="historicalplanfloor",
            table="history_sdb_fp_plan_floors",
        ),
        migrations.AlterModelTable(
            name="historicalproperty",
            table="history_sdb_properties",
        ),
        migrations.AlterModelTable(
            name="planfloor",
            table="sdb_fp_plan_floors",
        ),
        migrations.AlterModelTable(
            name="property",
            table="sdb_properties",
        ),
        migrations.AlterModelTable(
            name="scrapingjob",
            table="sdb_scraping_jobs",
        ),
    ]
