# Generated by Django 4.2.8 on 2025-04-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backup", "0009_rename_remaining_backup_tables"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="csvroomdimensions",
            name="calculated_floor_total_sq_area_imperial",
        ),
        migrations.RemoveField(
            model_name="csvroomdimensions",
            name="calculated_floor_total_sq_area_metric",
        ),
        migrations.RemoveField(
            model_name="historicalcsvroomdimensions",
            name="calculated_floor_total_sq_area_imperial",
        ),
        migrations.RemoveField(
            model_name="historicalcsvroomdimensions",
            name="calculated_floor_total_sq_area_metric",
        ),
        migrations.AddField(
            model_name="floorplan",
            name="update_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of times webhook processing updated this record.",
            ),
        ),
        migrations.AddField(
            model_name="historicalfloorplan",
            name="update_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of times webhook processing updated this record.",
            ),
        ),
        migrations.AlterField(
            model_name="allfloorscsvdata",
            name="actual_area_pixels",
            field=models.FloatField(
                blank=True, db_column="actual_area_pixels_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="allfloorscsvdata",
            name="calculated_area_imperial",
            field=models.FloatField(
                blank=True, db_column="calculated_area_imperial_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="allfloorscsvdata",
            name="calculated_floor_total_sq_area_imperial",
            field=models.FloatField(
                blank=True, db_column="calc_floor_total_imperial_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="allfloorscsvdata",
            name="calculated_floor_total_sq_area_metric",
            field=models.FloatField(
                blank=True, db_column="calc_floor_total_metric_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="allfloorscsvdata",
            name="calculated_sq_area_metric",
            field=models.FloatField(
                blank=True, db_column="calculated_sq_area_metric_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="allfloorscsvdata",
            name="max_area_imperial",
            field=models.FloatField(
                blank=True, db_column="max_area_imperial_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="allfloorscsvdata",
            name="max_area_metric",
            field=models.FloatField(
                blank=True, db_column="max_area_metric_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="allfloorscsvdata",
            name="max_area_pixels",
            field=models.FloatField(
                blank=True, db_column="max_area_pixels_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="allfloorscsvdata",
            name="max_x_pixels",
            field=models.FloatField(
                blank=True, db_column="max_x_pixels_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="allfloorscsvdata",
            name="max_y_pixels",
            field=models.FloatField(
                blank=True, db_column="max_y_pixels_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="allfloorscsvdata",
            name="min_x_pixels",
            field=models.FloatField(
                blank=True, db_column="min_x_pixels_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="allfloorscsvdata",
            name="min_y_pixels",
            field=models.FloatField(
                blank=True, db_column="min_y_pixels_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="allfloorscsvdata",
            name="pixel_ratio",
            field=models.FloatField(blank=True, db_column="pixel_ratio_csv", null=True),
        ),
        migrations.AlterField(
            model_name="allfloorscsvdata",
            name="scale_imperial",
            field=models.FloatField(
                blank=True, db_column="scale_imperial_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="allfloorscsvdata",
            name="scale_metric",
            field=models.FloatField(
                blank=True, db_column="scale_metric_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="allfloorsdata",
            name="csv_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="allfloorsdata",
            name="image_labelme_side_by_side_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="allfloorsdata",
            name="json_file_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="allfloorsdata",
            name="total_area_csv_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="csvroom",
            name="room_id",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="floorplan",
            name="floorplan_id",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="floorplan",
            name="original_url",
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="historicalallfloorscsvdata",
            name="actual_area_pixels",
            field=models.FloatField(
                blank=True, db_column="actual_area_pixels_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalallfloorscsvdata",
            name="calculated_area_imperial",
            field=models.FloatField(
                blank=True, db_column="calculated_area_imperial_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalallfloorscsvdata",
            name="calculated_floor_total_sq_area_imperial",
            field=models.FloatField(
                blank=True, db_column="calc_floor_total_imperial_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalallfloorscsvdata",
            name="calculated_floor_total_sq_area_metric",
            field=models.FloatField(
                blank=True, db_column="calc_floor_total_metric_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalallfloorscsvdata",
            name="calculated_sq_area_metric",
            field=models.FloatField(
                blank=True, db_column="calculated_sq_area_metric_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalallfloorscsvdata",
            name="max_area_imperial",
            field=models.FloatField(
                blank=True, db_column="max_area_imperial_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalallfloorscsvdata",
            name="max_area_metric",
            field=models.FloatField(
                blank=True, db_column="max_area_metric_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalallfloorscsvdata",
            name="max_area_pixels",
            field=models.FloatField(
                blank=True, db_column="max_area_pixels_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalallfloorscsvdata",
            name="max_x_pixels",
            field=models.FloatField(
                blank=True, db_column="max_x_pixels_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalallfloorscsvdata",
            name="max_y_pixels",
            field=models.FloatField(
                blank=True, db_column="max_y_pixels_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalallfloorscsvdata",
            name="min_x_pixels",
            field=models.FloatField(
                blank=True, db_column="min_x_pixels_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalallfloorscsvdata",
            name="min_y_pixels",
            field=models.FloatField(
                blank=True, db_column="min_y_pixels_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalallfloorscsvdata",
            name="pixel_ratio",
            field=models.FloatField(blank=True, db_column="pixel_ratio_csv", null=True),
        ),
        migrations.AlterField(
            model_name="historicalallfloorscsvdata",
            name="scale_imperial",
            field=models.FloatField(
                blank=True, db_column="scale_imperial_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalallfloorscsvdata",
            name="scale_metric",
            field=models.FloatField(
                blank=True, db_column="scale_metric_csv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalallfloorsdata",
            name="csv_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="historicalallfloorsdata",
            name="image_labelme_side_by_side_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="historicalallfloorsdata",
            name="json_file_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="historicalallfloorsdata",
            name="total_area_csv_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcsvroom",
            name="room_id",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalfloorplan",
            name="floorplan_id",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="historicalfloorplan",
            name="original_url",
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="historicalplanfloor",
            name="csv_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="historicalplanfloor",
            name="image_side_by_side_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="historicalplanfloor",
            name="image_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="historicalplanfloor",
            name="json_file_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="historicalplanfloor",
            name="label_me_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="historicalplanfloor",
            name="labelme_image_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="planfloor",
            name="csv_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="planfloor",
            name="image_side_by_side_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="planfloor",
            name="image_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="planfloor",
            name="json_file_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="planfloor",
            name="label_me_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="planfloor",
            name="labelme_image_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
