# Generated by Django 4.2.19 on 2025-03-13 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backup", "0002_backupuser_backupanalysistask_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupAllFloorsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("json_file_url", models.URLField()),
                ("csv_url", models.URLField()),
                ("total_area_csv_url", models.URLField()),
                ("image_labelme_side_by_side_url", models.URLField()),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BackupCsvFloor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("floor_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "calculated_total_area_metric",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "calculated_total_area_imperial",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "all_floors_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_csv_floors",
                        to="backup.backupallfloor<lfloorsdata",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BackupCsvRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("room_name", models.CharField(blank=True, max_length=100, null=True)),
                ("is_segment", models.CharField(blank=True, max_length=50, null=True)),
                ("room_id", models.FloatField(blank=True, null=True)),
                ("no_of_doors", models.FloatField(blank=True, null=True)),
                ("no_of_windows", models.FloatField(blank=True, null=True)),
                ("no_of_room_points", models.FloatField(blank=True, null=True)),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_rooms",
                        to="backup.backupcsvfloor",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BackupFloorPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("floorplan_id", models.CharField(max_length=255)),
                ("original_url", models.URLField()),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BackupFloorPlanAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.CharField(max_length=255)),
                ("user_id", models.CharField(max_length=255)),
                ("property_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BackupPlanFloor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("floor", models.CharField(max_length=255)),
                ("label_me_url", models.URLField()),
                ("json_file_url", models.URLField()),
                ("image_url", models.URLField()),
                ("labelme_image_url", models.URLField()),
                ("csv_url", models.URLField()),
                ("image_side_by_side_url", models.URLField()),
                (
                    "floor_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_plan_floors",
                        to="backup.backupfloorplan",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="backupfloorplan",
            name="analysis_result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="backup_floor_plans",
                to="backup.backupfloorplananalysisresult",
            ),
        ),
        migrations.CreateModel(
            name="BackupCsvRoomScalingFactors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scale_metric", models.FloatField(blank=True, null=True)),
                ("scale_imperial", models.FloatField(blank=True, null=True)),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_scaling_factors",
                        to="backup.backupcsvroom",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BackupCsvRoomPixelData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("min_x_pixels", models.FloatField(blank=True, null=True)),
                ("min_y_pixels", models.FloatField(blank=True, null=True)),
                ("max_x_pixels", models.FloatField(blank=True, null=True)),
                ("max_y_pixels", models.FloatField(blank=True, null=True)),
                ("max_area_pixels", models.FloatField(blank=True, null=True)),
                ("actual_area_pixels", models.FloatField(blank=True, null=True)),
                ("pixel_ratio", models.FloatField(blank=True, null=True)),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_pixel_data",
                        to="backup.backupcsvroom",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BackupCsvRoomDimensions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dimensions_imperial",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dimensions_metric",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("max_area_metric", models.FloatField(blank=True, null=True)),
                ("max_area_imperial", models.FloatField(blank=True, null=True)),
                ("calculated_sq_area_metric", models.FloatField(blank=True, null=True)),
                (
                    "calculated_floor_total_sq_area_metric",
                    models.FloatField(blank=True, null=True),
                ),
                ("calculated_area_imperial", models.FloatField(blank=True, null=True)),
                (
                    "calculated_floor_total_sq_area_imperial",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_dimensions",
                        to="backup.backupcsvroom",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="backupallfloorsdata",
            name="floor_plan",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="backup_all_floors_data",
                to="backup.backupfloorplan",
            ),
        ),
    ]
