# Generated by Django 4.2.8 on 2025-03-27 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backup", "0003_backupallfloorsdata_backupcsvfloor_backupcsvroom_and_more"),
    ]

    operations = [
        # Remove fields from existing models
        migrations.RemoveField(
            model_name="backupproperty",
            name="user",
        ),
        # Rename fields on original model names before renaming models
        migrations.RenameField(
            model_name="backupcsvroomdimensions",
            old_name="room",
            new_name="csv_room",
        ),
        migrations.RenameField(
            model_name="backupcsvroompixeldata",
            old_name="room",
            new_name="csv_room",
        ),
        migrations.RenameField(
            model_name="backupcsvroomscalingfactors",
            old_name="room",
            new_name="csv_room",
        ),
        # Rename all models
        migrations.RenameModel(
            old_name="BackupAllFloorsData",
            new_name="AllFloorsData",
        ),
        migrations.RenameModel(
            old_name="BackupCsvFloor",
            new_name="CsvFloor",
        ),
        migrations.RenameModel(
            old_name="BackupFloorPlan",
            new_name="FloorPlan",
        ),
        migrations.RenameModel(
            old_name="BackupFloorPlanAnalysisResult",
            new_name="FloorPlanAnalysisResult",
        ),
        migrations.RenameModel(
            old_name="BackupPlanFloor",
            new_name="PlanFloor",
        ),
        migrations.RenameModel(
            old_name="BackupScrapingJob",
            new_name="ScrapingJob",
        ),
        migrations.RenameModel(
            old_name="BackupAnalysisTask",
            new_name="AnalysisTask",
        ),
        migrations.RenameModel(
            old_name="BackupCsvRoom",
            new_name="CsvRoom",
        ),
        migrations.RenameModel(
            old_name="BackupProperty",
            new_name="Property",
        ),
        migrations.RenameModel(
            old_name="BackupCsvRoomDimensions",
            new_name="CsvRoomDimensions",
        ),
        migrations.RenameModel(
            old_name="BackupCsvRoomPixelData",
            new_name="CsvRoomPixelData",
        ),
        migrations.RenameModel(
            old_name="BackupCsvRoomScalingFactors",
            new_name="CsvRoomScalingFactors",
        ),
        migrations.RenameField(
            model_name="csvroom",
            old_name="floor",
            new_name="csv_floor",
        ),
        # Delete BackupUser
        migrations.DeleteModel(
            name="BackupUser",
        ),
    ]
