# Generated by Django 4.2.8 on 2025-04-15 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backup", "0007_rename_csv_models_tables"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allfloorscsvdata",
            options={
                "verbose_name": "All Floors CSV Raw Row",
                "verbose_name_plural": "All Floors CSV Raw Rows",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalallfloorscsvdata",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical All Floors CSV Raw Row",
                "verbose_name_plural": "historical All Floors CSV Raw Rows",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaltotalareascsvdata",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Total Area Data",
                "verbose_name_plural": "historical Total Area Data",
            },
        ),
        migrations.AlterModelOptions(
            name="totalareascsvdata",
            options={
                "verbose_name": "Total Area Data",
                "verbose_name_plural": "Total Area Data",
            },
        ),
        migrations.RenameIndex(
            model_name="allfloorscsvdata",
            new_name="sdb_all_flo_all_flo_9cde74_idx",
            old_name="backup_allf_all_flo_c57ce0_idx",
        ),
        migrations.RenameIndex(
            model_name="allfloorscsvdata",
            new_name="sdb_all_flo_all_flo_51cab9_idx",
            old_name="backup_allf_all_flo_37df0d_idx",
        ),
        migrations.AlterField(
            model_name="allfloorscsvdata",
            name="all_floors_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_floors_csv_data",
                to="backup.allfloorsdata",
            ),
        ),
        migrations.AlterField(
            model_name="totalareascsvdata",
            name="all_floors_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="total_areas_csv_data",
                to="backup.allfloorsdata",
            ),
        ),
        migrations.AlterModelTable(
            name="allfloorscsvdata",
            table="sdb_all_floors_csv_data",
        ),
        migrations.AlterModelTable(
            name="historicalallfloorscsvdata",
            table="history_sdb_all_floors_csv_data",
        ),
        migrations.AlterModelTable(
            name="historicaltotalareascsvdata",
            table="history_sdb_total_areas_csv_data",
        ),
        migrations.AlterModelTable(
            name="totalareascsvdata",
            table="sdb_total_areas_csv_data",
        ),
    ]
